version: '3.8'

services:
  discord-bot:
    build: .
    container_name: discord-bot
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - SHEET_ID=${SHEET_ID}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - APP_SCRIPT_URL=${APP_SCRIPT_URL}
    ports:
      - "3000:3000"
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped